// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace EntityLibrary.Entity
{
    public partial class ChatprojectdbContext : DbContext
    {
        public ChatprojectdbContext()
        {
        }

        public ChatprojectdbContext(DbContextOptions<ChatprojectdbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<User> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Turkish_CI_AS");

            modelBuilder.Entity<Message>(entity =>
            {
                entity.Property(e => e.SendDate).HasColumnType("datetime");

                entity.HasOne(d => d.RecipientUser)
                    .WithMany(p => p.MessageRecipientUsers)
                    .HasForeignKey(d => d.RecipientUserId)
                    .HasConstraintName("FK_Messages_Users1");

                entity.HasOne(d => d.SenderUser)
                    .WithMany(p => p.MessageSenderUsers)
                    .HasForeignKey(d => d.SenderUserId)
                    .HasConstraintName("FK_Messages_Users");
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.Property(e => e.Mail).HasMaxLength(50);

                entity.Property(e => e.Name).HasMaxLength(50);

                entity.Property(e => e.Password).HasMaxLength(50);

                entity.Property(e => e.Surname).HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}