// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace EntityLibrary.Entity
{
    public partial class User
    {
        public User()
        {
            MessageRecipientUsers = new HashSet<Message>();
            MessageSenderUsers = new HashSet<Message>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Mail { get; set; }
        public string Password { get; set; }

        public virtual ICollection<Message> MessageRecipientUsers { get; set; }
        public virtual ICollection<Message> MessageSenderUsers { get; set; }
    }
}